spring.application.name=crud

# --- Database connection ---
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}